url: https://jhonysc43.github.io/agencia/
baseurl: /agency-jekyll-theme/

# Site settings
title: JSC Freela
email: jsc.freela@gmail.com
description: Meu nome é Jhonatan, sou desenvolvedor de aplicativos Android, Websites, Landing page e e-commerce, conhecimentos sólidos em SCSS, JavaScript e Angular, amante por tecnologia, e minha na área da programação é de que, meu trabalho só se torna um sucesso quando meus clientes alcançam o sucesso,  alavancando suas vendas e capitando mais clientes por intermédio de minhas criações, isso para mim, não tem preço.


# Team names, titles and social links
people:
- name: Jhonatan Santos
  pic: 1
  position: Desenvolvedor de aplicativos
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
